steps:
  - name: "gcr.io/kaniko-project/executor:latest"
    args: ['--destination=gcr.io/$PROJECT_ID/trucks',
         '--cache=true']
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "trucks",
        "--allow-unauthenticated",
        "--image=gcr.io/$PROJECT_ID/trucks",
        "--update-env-vars=NEO4J_URI=neo4j://34.83.114.34:7687, NEO4J_USER=neo4j",
        "--platform",
        "managed",
        "--region=us-central1",
      ]
